repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^mmpose/
    -   id: end-of-file-fixer
        exclude: ^mmpose/
    -   id: check-yaml
        exclude: ^mmpose/
    # -   id: check-added-large-files
    -   id: check-merge-conflict
        exclude: ^mmpose/
    -   id: check-toml
        exclude: ^mmpose/
    -   id: debug-statements
        exclude: ^mmpose/

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3
        exclude: ^mmpose/

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
    -   id: ruff
        args: [
            "--fix",
            "--exit-non-zero-on-fix",
            "--select=E,F,B,W,I,F401",
        ]
        exclude: ^mmpose/
    -   id: ruff-format
        exclude: ^mmpose/

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black"]
        exclude: ^mmpose/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests]
        args: [--ignore-missing-imports]
        exclude: ^mmpose/
